profile-name : beta

spring:
  jpa:
    hibernate:
      ddl-auto: none    # create-drop #create #none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:tcp://localhost/~/webservice  #
    url:  jdbc:h2:mem:testdb
    #    jdbc:mariadb://okr-service-db.cgr3qj0mggqm.ap-northeast-2.rds.amazonaws.com:3306/okr_service_db
    username: sa
    password: